### ISSUE TITLE
Revoking permission does not trigger a notification

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-issues#60]
The PMP implementation of pubsubhubbub (see [the notification docs](https://github.com/publicmediaplatform/pmpdocs/wiki/Notifications-Usage)) defines these topics:

1. `/topics/updated` - feed of any existing PMP doc that has been updated, **excluding** docs you don't have access to (due to permission links)
2. `/topics/deleted` - feed of absolutely every PMP doc that has been deleted (since the doc no longer exists, there is no permissions check)

While testing the Wordpress plugin notifications endpoint, I discovered that (1) prevents notifying anyone about revoked access to a document.  Imagine this:

* User A publishes a public doc (no permission links)
* User B pulls down that doc to their wordpress site
* User A adds a permission link to the doc, making it private to themselves
* User B never hears about this change, due to the exclusions in (1)

**Comment by cavis** [comment]
@scottsmith130 any ideas on this one?  The only solution I can think of is to change (1) to be a true "firehose" of modified guids, whether you have access to them or not.

**Comment by scottsmith130** [comment]
Well, I'm not sure that the /topics/updated feed was ever meant to notify anyone of their rights to view a document.  If you have already pulled the content for the document and have it on your site, if permissions to that doc are later revoked, whether the user is notified or not, they still have access to all the content that they already had pulled from PMP.  So notifying them that they no longer have access would only serve to perhaps help the user know they should remove the doc from their site.  

Changing the update topic so that it becomes a true "firehose" of updated guids might not have the desired effect.  If someone sees that change, and then tries to get the updated doc, they will probably get a 404 (I believe we set it up to not actually tell someone they are unauthorized, only that the doc is not found).  But what if the 404 came from some other reason - how would the revoked user know the reason they can't get the doc is specifically because they no longer have access?  I suppose in this case if they get a 404 they could just assume the doc no longer exists and just remove it from their own site, regardless of the reason the doc doesn't exist.  Not sure if that is good reasoning or not.

I suppose an update topic just returning all guids regardless could be okay as long as the data contained in the notifications is reduced - maybe have the notifications only give the guid and/or URL of the doc that was updated and nothing else.  A revoked access means the user shouldn't see any content in that doc, not even the title.

**Comment by cavis** [comment]
Thanks for the thought-storm.  Yeah, this whole notifications + permissions thing is problematic, unless the PMP were to retain previous revisions of the doc.  Per #23 we're already revealing deleted `titles` and `guids` to all users.

FWIW, the PMP does return 403's these days.  The idea being it's hard to gleam anything interesting from just knowing a GUID exists.  Plus, our users are very well behaved!

I'm actually leaning towards making `topics/updated` a true firehose, and just giving away the titles.  Which would bring it into line with `topics/deleted`, as far as what's included.  (And removing the titles might be seen as non-backwards compatible - and possibly not inline with the pubsubhubbub 0.3 spec).

I'm going to check around to see if anyone's actually using the notifications `<title>`.  If not, I could just set it to also be the document `GUID`.  Problem solved!

**Comment by scottsmith130** [comment]
I think the original intent of using 404 instead of 403 was to hide the fact from somebody that they didn't have access to a document that someone else might have access to.  I think it might have been more of a political consideration than anything else.  Personally, I'd rather just return the 403 that HTTP intends anyway.

PSHB basically uses RSS so if RSS requires the title, then I guess we have to leave it.  But I like the idea of just using the guid as the title.  Seriously, anyone getting the notifications is just going to look up the full document anyway.  I think that the notifications could eventually be used to send the entire content of the document to subscribers so that they don't have to retrieve the doc again, but I don't think we ever implemented that, and it also seemed somewhat pointless to force a Collection.Doc into an RSS format anyway.

**Comment by cavis** [comment]
After checking around, I opted for the "<title>GUID</title>" option.  Should be entirely compatible with existing CMS subscribers, which are already ignoring the title, and re-fetching the doc for any GUIDs it knows about.

Deployed to sandbox to do some testing.  Will probably ship to production along with the scope=preview (public metadata) thing.

**Comment by cavis** [comment]
This has been deployed!
